language: php

env:
  secure: VygEKQhqIVN+temwbB8d+qrE7DivzxvmVLTbLilBFnywdpIiIRw/Kypv3RrFIhNCg0cyIRg6v7buvmJ8F0bbLDm0kHAXfaUCjOm8CXxq4cBUJDIQg5yCys64UKB08DfUBhNFb/HY1nnQdqTzqzEBhcgDnNd8jZWTok9QLd68VAk=

cache:
  directories:
    - $HOME/.composer/cache

git:
  depth: 10

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly
  fast_finish: true

before_script:
  - composer config --global github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer self-update --no-interaction --no-progress
  - composer install --no-interaction --no-progress --prefer-dist --profile -v

script:
  - vendor/bin/phpunit
