language: php

before_script:
  - composer self-update -n
  - composer install -o -n

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

script:
  - vendor/bin/phpcs --standard=PSR2 source/
  - vendor/bin/phpunit --strict --testdox
