language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7
  fast_finish: true

before_script:
  - composer self-update -n
  - composer install -o -n

script:
  - vendor/bin/phpunit
